client_config_backend: settings
client_config:
  client_id: 356461330409-b90qfdootenrc38ke37j2vlv0qir403b.apps.googleusercontent.com
  client_secret: bFLI1uD6bAq5AUrhSjVq_jKn

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
